export { default as Contact } from './Contact'
export { default as DotGroup } from './DotGroup'
export { default as Landing } from './Landing'
export { default as MySkills } from './MySkills'
export { default as Navbar } from './Navbar'
export { default as Projects } from './Projects'
export { default as Testimonials } from './Testimonials'
export { default as Footer } from './Footer'
